### ISSUE TITLE
heed error; No space left on device: MeiliSearch\Exceptions\HTTPRequestException

### ISSUE THREAD

**Issue by nlivingstone** [shokme/laravel-scout-meilisearch#62]
We have a job that updates our product database. While running this job, we keep running into os error 32: heed error; No space left on device.

Have checked diskspace and inode utilization however plenty are available for use. Have updated to the newest version of the meilisearch-laravel-scout client yet the issue still persists.

This issue occurs when updating a database record that uses the searchable trait.

```
"guzzlehttp/guzzle": "^7.2",
"laravel/framework": "^7.0",
"laravel/scout": "^8.3",
"meilisearch/meilisearch-laravel-scout": "^0.12.0",
```

Stacktrace:
```
[2020-11-24 12:05:08] production.ERROR: heed error; No space left on device (os error 28) {"exception":"[object] (MeiliSearch\\Exceptions\\HTTPRequestException(code: 500): heed error; No space left on device (os error 28) at /home/backend/app/vendor/meilisearch/meilisearch-php/src/Http/Client.php:182)
[stacktrace]
#0 /home/backend/app/vendor/meilisearch/meilisearch-php/src/Http/Client.php(165): MeiliSearch\\Http\\Client->parseResponse()
#1 /home/backend/app/vendor/meilisearch/meilisearch-php/src/Http/Client.php(101): MeiliSearch\\Http\\Client->execute()
#2 /home/backend/app/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesDocuments.php(29): MeiliSearch\\Http\\Client->post()
#3 /home/backend/app/vendor/meilisearch/meilisearch-laravel-scout/src/Engines/MeilisearchEngine.php(59): MeiliSearch\\Endpoints\\Indexes->addDocuments()
#4 /home/backend/app/vendor/laravel/scout/src/Searchable.php(63): Meilisearch\\Scout\\Engines\\MeilisearchEngine->update()
#5 /home/backend/app/vendor/laravel/scout/src/Searchable.php(42): App\\Models\\Product->queueMakeSearchable()
#6 /home/backend/app/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(114): Illuminate\\Database\\Eloquent\\Collection->Laravel\\Scout\\{closure}()
#7 /home/backend/app/vendor/laravel/scout/src/Searchable.php(154): Illuminate\\Support\\Collection->__call()
#8 /home/backend/app/vendor/laravel/scout/src/ModelObserver.php(69): App\\Models\\Product->searchable()
#9 /home/backend/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(401): Laravel\\Scout\\ModelObserver->saved()
#10 /home/backend/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#11 /home/backend/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#12 /home/backend/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(771): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#13 /home/backend/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(742): Illuminate\\Database\\Eloquent\\Model->finishSave()
#14 /home/backend/app/app/Jobs/BatchUpdateProducts.php(71): Illuminate\\Database\\Eloquent\\Model->save()
#15 /home/backend/app/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(90): App\\Jobs\\BatchUpdateProducts->App\\Jobs\\{closure}()
#16 /home/backend/app/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(113): Illuminate\\Redis\\Limiters\\DurationLimiter->block()
#17 /home/backend/app/app/Jobs/BatchUpdateProducts.php(77): Illuminate\\Redis\\Limiters\\DurationLimiterBuilder->then()
#18 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\BatchUpdateProducts->handle()
#19 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#23 /home/backend/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#24 /home/backend/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#25 /home/backend/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/backend/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#27 /home/backend/app/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(53): Illuminate\\Bus\\Dispatcher->dispatchNow()
#28 /home/backend/app/app/Console/Commands/ProductsUpdate.php(62): App\\Jobs\\BatchUpdateProducts::dispatchNow()
#29 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\ProductsUpdate->handle()
#30 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#32 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /home/backend/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#34 /home/backend/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#35 /home/backend/app/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#36 /home/backend/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#37 /home/backend/app/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#38 /home/backend/app/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /home/backend/app/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#40 /home/backend/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#41 /home/backend/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#42 /home/backend/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
```

**Comment by MarinPostma** [comment]
Hello! What platform are you on?

**Comment by nlivingstone** [comment]
Hello @MarinPostma

Experiencing this issue on multiple versions of Ubuntu Server

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
```

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
```

**Comment by MarinPostma** [comment]
Uhmm, is the --db-path set to a path on a disk with sufficient storage? It could also be related to the fact that the db is not able to complete it's transaction while indexing because it's running out of space, what amount of documents are you indexing in one go?

**Comment by nlivingstone** [comment]
The Meilisearch instance was created using the DigitalOcean image. The --db-path was set to /var/lib/meilisearch/data.ms. 

Deleted data.ms, restarted and reimported the documents seems to have fixed the issue. However I'm curious as to how data.ms grew to occupy 55GB. After reimporting the data, am currently sitting at 313 mb

**Comment by curquiza** [comment]
Hello @nlivingstone!
Great to read this fixes the issue, I close it then! And thanks for your feedback!
If you still encounter this kind of issue, feel free to open an issue in the [MeiliSearch repository](https://github.com/meilisearch/MeiliSearch) (since it's not linked to the laravel plugin) with you detailed steps 🙂

Here are more docs about storage that might help you: https://docs.meilisearch.com/resources/about_storage.html
